apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-users
  namespace: backstage
data:
  users.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: craigedmunds
    spec:
      profile:
        displayName: Craig Edmunds
        email: craig.edmunds@gmail.com
      memberOf: []
