apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eda-mesh-lob-service-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/craigedmunds/argocd-eda.git
      revision: {{ .Values.feature_branch }}
      directories:
      - path: 'eda/mesh/lobs/{{.Values.name}}/*'
      values:
        service: '{{`{{ .path.basename }}`}}'

  template:
    metadata:
      name: "eda-mesh-{{ .Values.name }}-{{`{{ .values.service }}`}}"
    spec:
      project: "eventing"
      sources:
        - repoURL: https://github.com/craigedmunds/argocd-eda.git
          targetRevision: {{ .Values.feature_branch }}
          ref: lob

        - repoURL: https://github.com/craigedmunds/argocd-eda.git
          targetRevision: {{ .Values.feature_branch }}
          path: 'eda/helm/mesh-lob-service'
          helm:
            fileParameters:
            - name: asyncapispec
              path: $lob/eda/mesh/lobs/{{.Values.name}}/{{`{{ .values.service }}`}}/asyncapi.yaml
        
            valueFiles:
            - $lob/eda/mesh/lobs/{{.Values.name}}/{{`{{ .values.service }}`}}/service.yaml
            
            parameters:
              - name: lob
                value: "{{.Values.name}}"
              - name: name
                value: '{{`{{ .values.service }}`}}'
              - name: feature_branch
                value: "{{ .Values.feature_branch }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "eda-mesh-{{.Values.name}}"

      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
          enabled: true
