apiVersion: v1
kind: Namespace
metadata:
  labels:
    
    # These two labels are used by ESO to add the rabbit secret
    apim/service.type: mesh-lob
    apim/deps.rabbitmq: 'true'
  name: eda-mesh-{{.Values.name}}