apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  labels:
    app: camel-k-mesh
  name: integration-platform
  namespace: camel-k-mesh
spec:
  build:
    registry:
      address: ghcr.io
      organization: craigedmunds
      insecure: true
      secret: ghcr-classic