apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-namespace.yaml
  - argocd-cmd-params-cm.yaml
  - argocd-config-map.yaml
  - argocd-ingress.yaml
  - argocd-projects.yaml