apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
  - host: rabbitmq.lab.ctoaas.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eda-mesh
            port:
              name: management
  - host: rabbitmq.lab.local.ctoaas.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eda-mesh
            port:
              name: management
  tls:
  - hosts:
    - rabbitmq.lab.ctoaas.co
    - rabbitmq.lab.local.ctoaas.co
    secretName: rabbitmq-ctoaas-tls
