apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: image-factory-kargo

resources:
  - namespace.yaml
  - project.yaml
  - warehouse-backstage.yaml
  - analysis-template.yaml
  - stage-analyze-dockerfile.yaml
  - stage-analyzed.yaml

configMapGenerator:
  - name: image-factory-analysis
    files:
      - app.py=../../apps/image-factory/app.py
      - pyproject.toml=../../apps/image-factory/pyproject.toml
