apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - namespace.yaml
  
  # Install operator
  - https://strimzi.io/install/latest?namespace=kafka
  
  # Install a single node shared cluster for things that want it
  - https://strimzi.io/examples/latest/kafka/kafka-single-node.yaml

# patches:
  # No longer needed - control plane taint removed globally in lab environment
  # - path: kafka-tolerations-patch.yaml