apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arc-systems

resources:
  - namespace.yaml
  - cluster-external-secret.yaml
  - service-account.yaml
  - helm-release.yaml
  - runner-scale-set.yaml

# Common labels
commonLabels:
  app.kubernetes.io/name: arc
  app.kubernetes.io/component: runner-controller
  app.kubernetes.io/managed-by: kustomize
