apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - traefik-namespace.yaml

helmChartInflationGenerator:
  - chartName: traefik
    chartRepoUrl: https://traefik.github.io/charts
    chartVersion: 32.1.1
    releaseName: traefik
    releaseNamespace: traefik
    values: values.yaml