apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - traefik-namespace.yaml


helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 32.1.1
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
    includeCRDs: true