apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ArgoCD Applications (still managed by ArgoCD)
  - central-secret-store-app.yaml
  - external-secrets
  # - external-secrets-app.yaml
  # - camel-karavan-app.yaml
  
  # Direct installations (no longer ArgoCD applications)
  - cert-manager/
  # - rabbitmq-operator/
  - strimzi/
  - argo-rollouts/
  - kargo/
  # - prometheus/