apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - central-secret-store-app.yaml
  - kargo-app.yaml
  - argo-rollouts-app.yaml
  - camel-karavan-app.yaml
  - cert-manager-app.yaml
  - kyverno-app.yaml
  - prometheus-app.yaml
  - rabbitmq-app.yaml