apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - warehouse.yaml
  - stage-dev.yaml
  - stage-staging.yaml
  - stage-production.yaml
  - analysis-template.yaml
