apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: eda-mesh-{{.Values.lob}}-{{.Values.name}}
    backstage.io/kubernetes-id: eda-mesh-{{.Values.lob}}-{{.Values.name}}
  name: eda-mesh-{{.Values.lob}}-{{.Values.name}}-jbang-config
  namespace: eda-mesh-{{.Values.lob}}
data:
  integration.yaml: |
{{ tpl (.Files.Get "integration.yaml") . | indent 4 }}