apiVersion: v1
kind: Service
metadata:
  labels:
    app: eda-mesh-{{.Values.lob}}-{{.Values.name}}
    app.kubernetes.io/runtime: camel
    backstage.io/kubernetes-id: eda-mesh-{{.Values.lob}}-{{.Values.name}}
  name: eda-mesh-{{.Values.lob}}-{{.Values.name}}-jbang
  namespace: eda-mesh-{{.Values.lob}}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: eda-mesh-{{.Values.lob}}-{{.Values.name}}-jbang
  type: ClusterIP
