apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arc-systems

bases:
  - ../../base

# Lab-specific patches
patchesStrategicMerge:
  - runner-scale-set-patch.yaml

# Lab-specific labels
commonLabels:
  environment: lab
