apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage-catalog-api

helmGlobals:
  chartHome: ../../../helm

helmCharts:
  - name: uv-service
    releaseName: backstage-catalog-api
    valuesFile: values.yaml

resources:
- namespace.yaml
- configmap.yaml
- clusterrole.yaml
- clusterrolebinding.yaml