apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - confluent-operator.yaml
  - confluent.yaml
  # - grafana.yaml
  - kyverno.yaml
  - prometheus.yaml
  - rabbitmq.yaml
