apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-rollouts.yaml
  # - argocd-ingress.yaml  # Removed - using IngressRoute in overlays instead
  - camel-karavan.yaml
  - central-secret-store.yaml
  - cert-manager.yaml
  # - confluent-operator.yaml
  # - confluent.yaml
  # - grafana.yaml
  - kargo.yaml
  - kyverno.yaml
  - prometheus.yaml
  - rabbitmq.yaml
  # - verdaccio.yaml
