apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage-catalog-api

helmGlobals:
  chartHome: ../../../../helm

helmCharts:
  - name: uv-service
    releaseName: backstage-catalog-api
    valuesFile: values.yaml

configMapGenerator:
  - name: backstage-catalog-api-api-config
    files:
      - app.py=../../../services/backstage-catalog-api/app.py
      - pyproject.toml=../../../services/backstage-catalog-api/pyproject.toml

resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml