apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: camel-karavan
  namespace: camel-karavan
  labels:
    ingress.ctoaas.co/managed: "true"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: camel-karavan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: karavan
            port:
              name: https