apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd
  - eda
  - backstage
  - image-factory
  - supporting-applications
  - seed-app

generatorOptions:
  disableNameSuffixHash: true