apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: camel-k-mesh-lob-service-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/craigedmunds/argocd-eda.git
      revision: HEAD
      directories:
      - path: 'mesh/lobs/{{.Values.name}}/*'
      values:
        service: '{{`{{ .path.basename }}`}}'

  template:
    metadata:
      name: "camel-k-mesh-{{ .Values.name }}-{{`{{ .values.service }}`}}"
    spec:
      project: "eventing"
      sources:
        - repoURL: https://github.com/craigedmunds/argocd-eda.git
          ref: lob
          directory:
            recurse: true
            include: '**/*.yaml'
        - repoURL: https://github.com/craigedmunds/argocd-eda.git
          targetRevision: HEAD
          path: 'helm/mesh-lob-service'
          helm:
            valueFiles:
            - $lob/mesh/lobs/{{.Values.name}}/{{`{{ .values.service }}`}}/asyncapi.yaml
            values: |
              apiDefinition: |
                asyncapi: '3.0.0'
                info:
                  title: User Service
                  version: '1.0.0'
                  description: |
                    This specification describes user-related events published by the User Service.
                    The `UserCreated` event is emitted when a new user account is successfully created.

                defaultContentType: application/cloudevents+json

            # valuesObject:
            #   apiDefinition:
            #     asyncapi: '3.0.0'
            #     info:
            #       title: User Service
            #       version: '1.0.0'
            #       description: |
            #         This specification describes user-related events published by the User Service.
            #         The `UserCreated` event is emitted when a new user account is successfully created.

            #     defaultContentType: application/cloudevents+json

            parameters:
              - name: lob
                value: "{{.Values.name}}"
              - name: name
                value: '{{`{{ .values.service }}`}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: "camel-k-mesh-{{.Values.name}}"

      syncPolicy:
        syncOptions:
        - CreateNamespace=true
