apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- producers.yaml
- consumers.yaml
- services.yaml
- lob-applications.yaml
# Kyverno approach (replaced by ESO)
# - kyverno-copy-rabbit-secret.yaml
# - kyverno-rbac.yaml
# ESO approach for RabbitMQ secrets
- eda-mesh-secret-store.yaml
- eso-rbac.yaml
- eso-rabbitmq-secret.yaml
- backstage.yaml

# components:
#   - ../_common/components/argocd-branch-targetrevision