apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eda-mesh-lob-applications
  namespace: argocd
  labels:
    repo: argocd-eda
    argocd-branch-targetrevision: "true"
    source-type: helm
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/craigedmunds/argocd-eda.git
      revision: main
      directories:
      - path: eda/mesh/lobs/*
  template:
    metadata:
      
      # this path is escaped for consumption by argocd rather than helm.
      name: 'eda-mesh-{{.path.basename}}'
    spec:
      project: "eventing"
      source:
        repoURL: https://github.com/craigedmunds/argocd-eda.git
        targetRevision: main
        path: 'eda/helm/mesh-lob'
        helm:
          parameters:
            - name: name
              value: '{{.path.basename}}'
            - name: feature_branch
              value: main
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
          enabled: true