apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage-dev

resources:
  - ../../

# Override values for dev environment
patchesStrategicMerge:
  - values-patch.yaml

# Image will be updated by Kargo
images:
  - name: ghcr.io/craigedmunds/backstage
    newTag: 1.0.0  # Kargo will update this
