apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-values
data:
  values.yaml: |
    backstage:
      image:
        repository: ghcr.io/craigedmunds/backstage
        tag: 1.0.0  # Kargo will update this
      
      appConfig:
        app:
          title: Backstage (Dev)
          baseUrl: https://backstage-dev.127.0.0.1.nip.io
        backend:
          baseUrl: https://backstage-dev.127.0.0.1.nip.io
          cors:
            origin: https://backstage-dev.127.0.0.1.nip.io
    
    ingress:
      host: backstage-dev.127.0.0.1.nip.io
