[project]
name = "cdk8s-cli"
version = "0.1.0"
requires-python = ">=3.10,<3.14"
dependencies = [
    "constructs~=10.4.3",
    "cdk8s~=2.68.0",
    "pyyaml"
]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

