apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  labels:
    repo: argocd-eda
    environment: local
  annotations:
    kargo.akuity.io/authorized-stage: backstage-kargo:local
spec:
  project: eventing
  source:
    repoURL: https://github.com/craigedmunds/argocd-eda.git
    targetRevision: feature/backstage-events
    path: kustomize/backstage/overlays/local
      
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
