apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  labels:
    repo: argocd-eda
    environment: local
    branch-strategy: multisource
spec:
  project: eventing
  sources:
    - repoURL: https://github.com/craigedmunds/argocd-eda.git
      targetRevision: HEAD
      path: kustomize/backstage/overlays/local
    - repoURL: https://github.com/craigedmunds/argocd-eda.git
      targetRevision: HEAD
      path: kustomize/backstage/kargo
      
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
