apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-kargo
  namespace: argocd
  labels:
    repo: argocd-eda
    environment: local
    component: kargo
spec:
  project: eventing
  source:
    repoURL: https://github.com/craigedmunds/argocd-eda.git
    targetRevision: feature/backstage-events
    path: kustomize/backstage-kargo
      
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage-kargo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true