apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: eda-mesh-consumer-{{.Values.name}}
    backstage.io/kubernetes-id: eda-mesh-consumer-{{.Values.name}}
  name: eda-mesh-consumer-{{.Values.name}}-config
  namespace: eda-mesh-consumer-{{.Values.name}}
data:
  integration.yaml: |
{{ tpl (.Files.Get "integration.yaml") . | indent 4 }}