apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eda-mesh-consumer-{{ .Values.name }}-rabbit-secret-read
  namespace: eda-mesh-consumer-{{.Values.name}}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["eda-mesh-rabbit-user"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eda-mesh-consumer-{{.Values.name}}-rabbit-secret-read
  namespace: eda-mesh-consumer-{{.Values.name}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eda-mesh-consumer-{{.Values.name}}-rabbit-secret-read
subjects:
  - kind: ServiceAccount
    name: default
    namespace: eda-mesh-consumer-{{.Values.name}}
