apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: headlamp

resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrolebinding.yaml

generatorOptions:
  disableNameSuffixHash: true

# # Create namespace with required labels using labels field
# labels:
#   - pairs:
#       secrets/kargo-admin-credentials: "true"

helmCharts:
  - name: headlamp
    releaseName: cluster
    repo: https://kubernetes-sigs.github.io/headlamp/
    version: 0.39.0
    namespace: headlamp
    valuesFile: values.yaml