apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

helmChartInflationGenerator:
  - chartRepoUrl: https://backstage.github.io/charts
    chartName: backstage
    chartVersion: 2.6.3
    releaseName: backstage
    values: values.yaml

resources:
  - namespace.yaml
  - k8s-rbac.yaml
  - configmap-catalog.yaml
  - configmap-rootlocation.yaml
  - ingress.yaml

generatorOptions:
  disableNameSuffixHash: true
