apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# helmChartInflationGenerator:
#   - chartRepoUrl: https://apache.github.io/camel-k/charts/
#     chartName: camel-k
#     chartVersion: 2.8.0

# resources:
# - base

resources:
- rabbitmq.yaml
# - backstage.yaml

configMapGenerator:
- name: test-asyncapi
  behavior: create
  namespace: camel-k-mesh-demo
  literals:
    - |
      apiDefinition.yaml=
        asyncapi: '3.0.0'
        info:
          title: User Service
          version: '1.0.0'
          description: |
            This specification describes user-related events published by the User Service.
            The `UserCreated` event is emitted when a new user account is successfully created.

        defaultContentType: application/cloudevents+json