
helmChartInflationGenerator:
  - chartHome: ../../../helm
    chartName: jbang-camel-integration
    releaseName: eda-mesh-producer-demo-user-created
    values: values.yaml

resources:
- confluent-topic.yaml
- jbang-configmap.yaml
