apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

resources:
  - ../../

patchesStrategicMerge:
  - values-patch.yaml

images:
  - name: ghcr.io/craigedmunds/backstage
    newTag: 1.0.0  # Kargo will update this
