apiVersion: v1
kind: Service
metadata:
  labels:
    app: camel-k-mesh-consumer-{{.Values.name}}
    app.kubernetes.io/runtime: camel
  name: camel-k-mesh-consumer-{{.Values.name}}-jbang
  namespace: camel-k-mesh-consumer-{{.Values.name}}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: camel-k-mesh-consumer-{{.Values.name}}
  type: ClusterIP
