lob: mistake-lob
name: mistake-service
domain: mistake-domain
subdomain: mistake-subdomain
owner: mistakeOwner

asyncapispec: |
  asyncapi: '3.0.0'
  info:
    title: Example Service
    version: '1.0.0'

  channels:
    mistakeEvent:
      description: Mistake Topic 
      bindings:
        kafka:
          topic: mistake-topic