apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage-catalog-api

helmChartInflationGenerator:
  - chartName: jbang-camel-integration
    
    # TODO : Figure out why i can't reference the chart from the helm folder
    # chartHome: ../../../../helm
    chartHome: charts
    
    releaseName: backstage-catalog-api
    values: values.yaml

resources:
# - charts/jbang-camel-integration
- namespace.yaml
- jbang-configmap.yaml