apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyverno

resources:
  - namespace.yaml

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    version: 3.2.6
    namespace: kyverno
    valuesInline:
      crds:
        install: true