apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Lab environment overlay - includes all capabilities and supporting applications
resources:
  - ../../../traefik
  - ../../../argocd
  - ../../../eda
  - ../../../backstage
  - ../../../image-factory
  - ../../../supporting-applications
  - ../../../../local-storage
  - mobile-ai-dev-seed.yaml
  # - ../../../seed-app
  # - patch-seed-application.yaml
  - letsencrypt-issuer.yaml

components:
  - ../../../../_common/components/argocd-branch-targetrevision


configMapGenerator:
  - name: argocd-branch-targetrevision
    namespace: argocd
    behavior: add
    literals:
      - targetRevision=feature/backstage-events


helmGlobals:
  chartHome: ../../../../../../helm

helmCharts:
  # Private ingress example (internal access only)
  - name: traefik-ingress
    releaseName: argocd
    valuesInline:
      service:
        name: argocd-server
        namespace: argocd
        port:
          name: http
      ingress:
        name: argocd-server-ingress
        accessPattern: internal
      domains:
        localDomainSuffix: lab.local.ctoaas.co
        name: argocd
      tls:
        enabled: true
        issuer: letsencrypt-prod
        secretName: argocd-ctoaas-tls

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    
# Lab-specific patches
patches:

  - target:
      kind: Application
      name: seed
    patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: feature/backstage-events
      - op: replace
        path: /spec/source/path
        value: platform/kustomize/seed/overlays/local/lab

  - target:
      kind: Application
      name: eda-mesh
    patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: feature/backstage-events
      - op: replace
        path: /spec/source/path
        value: eda/kustomize/mesh/overlays/lab