apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Lab environment overlay - includes all capabilities and supporting applications
resources:
  - ../../../traefik
  - ../../../argocd
  - ../../../eda
  - ../../../backstage
  - ../../../image-factory
  - ../../../supporting-applications
  # - ../../../seed-app
  # - patch-seed-application.yaml
  - letsencrypt-issuer.yaml

components:
  - ../../../../_common/components/argocd-branch-targetrevision

configMapGenerator:
  - name: argocd-branch-targetrevision
    namespace: argocd
    behavior: add
    literals:
      - targetRevision=feature/backstage-events

generatorOptions:
  disableNameSuffixHash: true

# Lab-specific patches
patches:
  - target:
      kind: Ingress
      name: argocd-server-ingress
    patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-prod
      - op: add
        path: /spec/tls
        value:
          - hosts:
            - argocd.lab.ctoaas.co
            - argocd.lab.local.ctoaas.co
            secretName: argocd-ctoaas-tls
      - op: replace
        path: /spec/rules
        value:
          - host: argocd.lab.ctoaas.co
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: argocd-server
                    port:
                      name: http
          - host: argocd.lab.local.ctoaas.co
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: argocd-server
                    port:
                      name: http

  - target:
      kind: Application
      name: seed
    patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: feature/backstage-events
      - op: replace
        path: /spec/source/path
        value: platform/kustomize/seed/overlays/local/lab

  - target:
      kind: Application
      name: eda-mesh
    patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: feature/backstage-events
      - op: replace
        path: /spec/source/path
        value: eda/kustomize/mesh/overlays/lab